<?php

/**
 * BaseAsset
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $file
 * @property string $hash
 * 
 * @method integer getId()   Returns the current record's "id" value
 * @method text    getFile() Returns the current record's "file" value
 * @method string  getHash() Returns the current record's "hash" value
 * @method Asset   setId()   Sets the current record's "id" value
 * @method Asset   setFile() Sets the current record's "file" value
 * @method Asset   setHash() Sets the current record's "hash" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseAsset extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('asset');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('file', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('hash', 'string', 32, array(
             'type' => 'string',
             'length' => 32,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}