<?php

/**
 * BaseCampaignStageUnit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $stage_id
 * @property text $type
 * @property integer $quantity
 * @property integer $x
 * @property integer $y
 * @property integer $time
 * @property CampaignStage $stage
 * 
 * @method integer           getStageId()  Returns the current record's "stage_id" value
 * @method text              getType()     Returns the current record's "type" value
 * @method integer           getQuantity() Returns the current record's "quantity" value
 * @method integer           getX()        Returns the current record's "x" value
 * @method integer           getY()        Returns the current record's "y" value
 * @method integer           getTime()     Returns the current record's "time" value
 * @method CampaignStage     getStage()    Returns the current record's "stage" value
 * @method CampaignStageUnit setStageId()  Sets the current record's "stage_id" value
 * @method CampaignStageUnit setType()     Sets the current record's "type" value
 * @method CampaignStageUnit setQuantity() Sets the current record's "quantity" value
 * @method CampaignStageUnit setX()        Sets the current record's "x" value
 * @method CampaignStageUnit setY()        Sets the current record's "y" value
 * @method CampaignStageUnit setTime()     Sets the current record's "time" value
 * @method CampaignStageUnit setStage()    Sets the current record's "stage" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCampaignStageUnit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('campaigns_stages_units');
        $this->hasColumn('stage_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('quantity', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('x', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('y', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('time', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('CampaignStage as stage', array(
             'local' => 'stage_id',
             'foreign' => 'id'));
    }
}