<?php

/**
 * BaseDefenseLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $defense_id
 * @property integer $level
 * @property integer $time
 * @property text $requirements
 * @property text $stats
 * @property Defense $defense
 * 
 * @method integer      getDefenseId()    Returns the current record's "defense_id" value
 * @method integer      getLevel()        Returns the current record's "level" value
 * @method integer      getTime()         Returns the current record's "time" value
 * @method text         getRequirements() Returns the current record's "requirements" value
 * @method text         getStats()        Returns the current record's "stats" value
 * @method Defense      getDefense()      Returns the current record's "defense" value
 * @method DefenseLevel setDefenseId()    Sets the current record's "defense_id" value
 * @method DefenseLevel setLevel()        Sets the current record's "level" value
 * @method DefenseLevel setTime()         Sets the current record's "time" value
 * @method DefenseLevel setRequirements() Sets the current record's "requirements" value
 * @method DefenseLevel setStats()        Sets the current record's "stats" value
 * @method DefenseLevel setDefense()      Sets the current record's "defense" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDefenseLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('defense_levels');
        $this->hasColumn('defense_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('time', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('requirements', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('stats', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Defense as defense', array(
             'local' => 'defense_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}