<?php

/**
 * BaseEquipmentLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $equipment_id
 * @property integer $level
 * @property integer $tier
 * @property integer $time
 * @property integer $upgrade_chance
 * @property integer $require_g
 * @property integer $require_e
 * @property integer $require_u
 * @property integer $require_c
 * @property integer $require_s
 * @property integer $stat_hp
 * @property integer $stat_range
 * @property integer $stat_rate
 * @property integer $stat_damage
 * @property integer $stat_targets
 * @property integer $stat_splash
 * @property boolean $stat_concussion
 * @property float $stat_defense
 * @property text $tags
 * @property Equipment $equipment
 * 
 * @method integer        getEquipmentId()     Returns the current record's "equipment_id" value
 * @method integer        getLevel()           Returns the current record's "level" value
 * @method integer        getTier()            Returns the current record's "tier" value
 * @method integer        getTime()            Returns the current record's "time" value
 * @method integer        getUpgradeChance()   Returns the current record's "upgrade_chance" value
 * @method integer        getRequireG()        Returns the current record's "require_g" value
 * @method integer        getRequireE()        Returns the current record's "require_e" value
 * @method integer        getRequireU()        Returns the current record's "require_u" value
 * @method integer        getRequireC()        Returns the current record's "require_c" value
 * @method integer        getRequireS()        Returns the current record's "require_s" value
 * @method integer        getStatHp()          Returns the current record's "stat_hp" value
 * @method integer        getStatRange()       Returns the current record's "stat_range" value
 * @method integer        getStatRate()        Returns the current record's "stat_rate" value
 * @method integer        getStatDamage()      Returns the current record's "stat_damage" value
 * @method integer        getStatTargets()     Returns the current record's "stat_targets" value
 * @method integer        getStatSplash()      Returns the current record's "stat_splash" value
 * @method boolean        getStatConcussion()  Returns the current record's "stat_concussion" value
 * @method float          getStatDefense()     Returns the current record's "stat_defense" value
 * @method text           getTags()            Returns the current record's "tags" value
 * @method Equipment      getEquipment()       Returns the current record's "equipment" value
 * @method EquipmentLevel setEquipmentId()     Sets the current record's "equipment_id" value
 * @method EquipmentLevel setLevel()           Sets the current record's "level" value
 * @method EquipmentLevel setTier()            Sets the current record's "tier" value
 * @method EquipmentLevel setTime()            Sets the current record's "time" value
 * @method EquipmentLevel setUpgradeChance()   Sets the current record's "upgrade_chance" value
 * @method EquipmentLevel setRequireG()        Sets the current record's "require_g" value
 * @method EquipmentLevel setRequireE()        Sets the current record's "require_e" value
 * @method EquipmentLevel setRequireU()        Sets the current record's "require_u" value
 * @method EquipmentLevel setRequireC()        Sets the current record's "require_c" value
 * @method EquipmentLevel setRequireS()        Sets the current record's "require_s" value
 * @method EquipmentLevel setStatHp()          Sets the current record's "stat_hp" value
 * @method EquipmentLevel setStatRange()       Sets the current record's "stat_range" value
 * @method EquipmentLevel setStatRate()        Sets the current record's "stat_rate" value
 * @method EquipmentLevel setStatDamage()      Sets the current record's "stat_damage" value
 * @method EquipmentLevel setStatTargets()     Sets the current record's "stat_targets" value
 * @method EquipmentLevel setStatSplash()      Sets the current record's "stat_splash" value
 * @method EquipmentLevel setStatConcussion()  Sets the current record's "stat_concussion" value
 * @method EquipmentLevel setStatDefense()     Sets the current record's "stat_defense" value
 * @method EquipmentLevel setTags()            Sets the current record's "tags" value
 * @method EquipmentLevel setEquipment()       Sets the current record's "equipment" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquipmentLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipment_level');
        $this->hasColumn('equipment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tier', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('time', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('upgrade_chance', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('require_g', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('require_e', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('require_u', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('require_c', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('require_s', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('stat_hp', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('stat_range', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('stat_rate', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('stat_damage', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('stat_targets', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('stat_splash', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('stat_concussion', 'boolean', null, array(
             'type' => 'boolean',
             ));
        $this->hasColumn('stat_defense', 'float', null, array(
             'type' => 'float',
             ));
        $this->hasColumn('tags', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Equipment as equipment', array(
             'local' => 'equipment_id',
             'foreign' => 'id'));
    }
}