<?php

/**
 * BaseMapRevard
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $value
 * @property text $rewards
 * 
 * @method integer   getId()      Returns the current record's "id" value
 * @method integer   getValue()   Returns the current record's "value" value
 * @method text      getRewards() Returns the current record's "rewards" value
 * @method MapRevard setId()      Sets the current record's "id" value
 * @method MapRevard setValue()   Sets the current record's "value" value
 * @method MapRevard setRewards() Sets the current record's "rewards" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMapRevard extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('map_rewards');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('value', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('rewards', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}