<?php

/**
 * BaseUnitLevels
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $unit_id
 * @property integer $level
 * @property text $requirements
 * @property text $stats
 * @property Unit $unit
 * 
 * @method integer    getUnitId()       Returns the current record's "unit_id" value
 * @method integer    getLevel()        Returns the current record's "level" value
 * @method text       getRequirements() Returns the current record's "requirements" value
 * @method text       getStats()        Returns the current record's "stats" value
 * @method Unit       getUnit()         Returns the current record's "unit" value
 * @method UnitLevels setUnitId()       Sets the current record's "unit_id" value
 * @method UnitLevels setLevel()        Sets the current record's "level" value
 * @method UnitLevels setRequirements() Sets the current record's "requirements" value
 * @method UnitLevels setStats()        Sets the current record's "stats" value
 * @method UnitLevels setUnit()         Sets the current record's "unit" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnitLevels extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('unit_levels');
        $this->hasColumn('unit_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('requirements', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('stats', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Unit as unit', array(
             'local' => 'unit_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}