<?php

/**
 * BaseCampaign
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $name
 * @property integer $unlock_level
 * @property Doctrine_Collection $stages
 * 
 * @method integer             getId()           Returns the current record's "id" value
 * @method text                getName()         Returns the current record's "name" value
 * @method integer             getUnlockLevel()  Returns the current record's "unlock_level" value
 * @method Doctrine_Collection getStages()       Returns the current record's "stages" collection
 * @method Campaign            setId()           Sets the current record's "id" value
 * @method Campaign            setName()         Sets the current record's "name" value
 * @method Campaign            setUnlockLevel()  Sets the current record's "unlock_level" value
 * @method Campaign            setStages()       Sets the current record's "stages" collection
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseCampaign extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('campaigns');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('name', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('unlock_level', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('CampaignStage as stages', array(
             'local' => 'id',
             'foreign' => 'campaign_id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE',
             'orderBy' => 'id'));
    }
}