<?php

/**
 * BasePlayerHistory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $player_id
 * 
 * @method integer       getId()        Returns the current record's "id" value
 * @method integer       getPlayerId()  Returns the current record's "player_id" value
 * @method PlayerHistory setId()        Sets the current record's "id" value
 * @method PlayerHistory setPlayerId()  Sets the current record's "player_id" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayerHistory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('player_history');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('player_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}