<?php

/**
 * BaseEquipmentLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $equipment_id
 * @property integer $level
 * @property integer $tier
 * @property integer $time
 * @property integer $upgrade_chance
 * @property array $requirements
 * @property array $stats
 * @property array $tags
 * @property Equipment $equipment
 * 
 * @method integer        getEquipmentId()    Returns the current record's "equipment_id" value
 * @method integer        getLevel()          Returns the current record's "level" value
 * @method integer        getTier()           Returns the current record's "tier" value
 * @method integer        getTime()           Returns the current record's "time" value
 * @method integer        getUpgradeChance()  Returns the current record's "upgrade_chance" value
 * @method array          getRequirements()   Returns the current record's "requirements" value
 * @method array          getStats()          Returns the current record's "stats" value
 * @method array          getTags()           Returns the current record's "tags" value
 * @method Equipment      getEquipment()      Returns the current record's "equipment" value
 * @method EquipmentLevel setEquipmentId()    Sets the current record's "equipment_id" value
 * @method EquipmentLevel setLevel()          Sets the current record's "level" value
 * @method EquipmentLevel setTier()           Sets the current record's "tier" value
 * @method EquipmentLevel setTime()           Sets the current record's "time" value
 * @method EquipmentLevel setUpgradeChance()  Sets the current record's "upgrade_chance" value
 * @method EquipmentLevel setRequirements()   Sets the current record's "requirements" value
 * @method EquipmentLevel setStats()          Sets the current record's "stats" value
 * @method EquipmentLevel setTags()           Sets the current record's "tags" value
 * @method EquipmentLevel setEquipment()      Sets the current record's "equipment" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquipmentLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipment_level');
        $this->hasColumn('equipment_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('tier', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('time', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('upgrade_chance', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('requirements', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('stats', 'array', null, array(
             'type' => 'array',
             ));
        $this->hasColumn('tags', 'array', null, array(
             'type' => 'array',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Equipment as equipment', array(
             'local' => 'equipment_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}