<?php

/**
 * BaseUnit
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $type
 * @property Doctrine_Collection $levels
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method text                getType()   Returns the current record's "type" value
 * @method Doctrine_Collection getLevels() Returns the current record's "levels" collection
 * @method Unit                setId()     Sets the current record's "id" value
 * @method Unit                setType()   Sets the current record's "type" value
 * @method Unit                setLevels() Sets the current record's "levels" collection
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUnit extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('units');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('type', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('UnitLevel as levels', array(
             'local' => 'id',
             'foreign' => 'unit_id'));
    }
}