<?php

/**
 * BaseTranslation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $id
 * @property string $lang
 * @property text $content
 * 
 * @method string      getId()      Returns the current record's "id" value
 * @method string      getLang()    Returns the current record's "lang" value
 * @method text        getContent() Returns the current record's "content" value
 * @method Translation setId()      Sets the current record's "id" value
 * @method Translation setLang()    Sets the current record's "lang" value
 * @method Translation setContent() Sets the current record's "content" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTranslation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('translation');
        $this->hasColumn('id', 'string', 255, array(
             'type' => 'string',
             'primary' => true,
             'length' => 255,
             ));
        $this->hasColumn('lang', 'string', 2, array(
             'type' => 'string',
             'primary' => true,
             'length' => 2,
             ));
        $this->hasColumn('content', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}