<?php

/**
 * BaseProxy
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $type
 * @property array $params
 * 
 * @method integer getId()     Returns the current record's "id" value
 * @method text    getType()   Returns the current record's "type" value
 * @method array   getParams() Returns the current record's "params" value
 * @method Proxy   setId()     Sets the current record's "id" value
 * @method Proxy   setType()   Sets the current record's "type" value
 * @method Proxy   setParams() Sets the current record's "params" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseProxy extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('proxy');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('type', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('params', 'array', null, array(
             'type' => 'array',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}