<?php

/**
 * BaseTokenLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $token_id
 * @property integer $level
 * @property array $stats
 * @property Token $token
 * 
 * @method integer    getTokenId()  Returns the current record's "token_id" value
 * @method integer    getLevel()    Returns the current record's "level" value
 * @method array      getStats()    Returns the current record's "stats" value
 * @method Token      getToken()    Returns the current record's "token" value
 * @method TokenLevel setTokenId()  Sets the current record's "token_id" value
 * @method TokenLevel setLevel()    Sets the current record's "level" value
 * @method TokenLevel setStats()    Sets the current record's "stats" value
 * @method TokenLevel setToken()    Sets the current record's "token" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTokenLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('token_level');
        $this->hasColumn('token_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('stats', 'array', null, array(
             'type' => 'array',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Token as token', array(
             'local' => 'token_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}