<?php

/**
 * BaseMapNode
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $map_id
 * @property integer $x
 * @property integer $y
 * @property integer $level
 * @property text $owner
 * @property integer $owner_id
 * @property text $collection
 * @property integer $collection_id
 * @property Map $map
 * 
 * @method integer getId()            Returns the current record's "id" value
 * @method integer getMapId()         Returns the current record's "map_id" value
 * @method integer getX()             Returns the current record's "x" value
 * @method integer getY()             Returns the current record's "y" value
 * @method integer getLevel()         Returns the current record's "level" value
 * @method text    getOwner()         Returns the current record's "owner" value
 * @method integer getOwnerId()       Returns the current record's "owner_id" value
 * @method text    getCollection()    Returns the current record's "collection" value
 * @method integer getCollectionId()  Returns the current record's "collection_id" value
 * @method Map     getMap()           Returns the current record's "map" value
 * @method MapNode setId()            Sets the current record's "id" value
 * @method MapNode setMapId()         Sets the current record's "map_id" value
 * @method MapNode setX()             Sets the current record's "x" value
 * @method MapNode setY()             Sets the current record's "y" value
 * @method MapNode setLevel()         Sets the current record's "level" value
 * @method MapNode setOwner()         Sets the current record's "owner" value
 * @method MapNode setOwnerId()       Sets the current record's "owner_id" value
 * @method MapNode setCollection()    Sets the current record's "collection" value
 * @method MapNode setCollectionId()  Sets the current record's "collection_id" value
 * @method MapNode setMap()           Sets the current record's "map" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMapNode extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('map_node');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('map_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('x', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('y', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('owner', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('owner_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('collection', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('collection_id', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Map as map', array(
             'local' => 'map_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}