<?php

/**
 * BaseHome
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $name
 * @property datetime $damage_protection
 * 
 * @method integer  getId()                Returns the current record's "id" value
 * @method text     getName()              Returns the current record's "name" value
 * @method datetime getDamageProtection()  Returns the current record's "damage_protection" value
 * @method Home     setId()                Sets the current record's "id" value
 * @method Home     setName()              Sets the current record's "name" value
 * @method Home     setDamageProtection()  Sets the current record's "damage_protection" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseHome extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('home');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('name', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('damage_protection', 'datetime', null, array(
             'type' => 'datetime',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}