<?php

/**
 * BaseMeltdown
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $value
 * 
 * @method integer  getId()    Returns the current record's "id" value
 * @method text     getValue() Returns the current record's "value" value
 * @method Meltdown setId()    Sets the current record's "id" value
 * @method Meltdown setValue() Sets the current record's "value" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseMeltdown extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('meltdown');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('value', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}