<?php

/**
 * BaseDefense
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $type
 * @property Doctrine_Collection $levels
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method text                getType()   Returns the current record's "type" value
 * @method Doctrine_Collection getLevels() Returns the current record's "levels" collection
 * @method Defense             setId()     Sets the current record's "id" value
 * @method Defense             setType()   Sets the current record's "type" value
 * @method Defense             setLevels() Sets the current record's "levels" collection
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDefense extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('defense');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('type', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('DefenseLevel as levels', array(
             'local' => 'id',
             'foreign' => 'defense_id',
             'orderBy' => 'level'));
    }
}