<?php

/**
 * BaseGeneralLevel
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $general_id
 * @property integer $level
 * @property text $requirements
 * @property text $stats
 * @property General $general
 * 
 * @method integer      getGeneralId()    Returns the current record's "general_id" value
 * @method integer      getLevel()        Returns the current record's "level" value
 * @method text         getRequirements() Returns the current record's "requirements" value
 * @method text         getStats()        Returns the current record's "stats" value
 * @method General      getGeneral()      Returns the current record's "general" value
 * @method GeneralLevel setGeneralId()    Sets the current record's "general_id" value
 * @method GeneralLevel setLevel()        Sets the current record's "level" value
 * @method GeneralLevel setRequirements() Sets the current record's "requirements" value
 * @method GeneralLevel setStats()        Sets the current record's "stats" value
 * @method GeneralLevel setGeneral()      Sets the current record's "general" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGeneralLevel extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('general_levels');
        $this->hasColumn('general_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('level', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             ));
        $this->hasColumn('requirements', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('stats', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('General as general', array(
             'local' => 'general_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE',
             'onUpdate' => 'CASCADE'));
    }
}