<?php

/**
 * BaseChat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $room
 * @property text $message
 * @property integer $sender_id
 * @property text $sender
 * @property integer $alliance_id
 * @property text $alliance
 * 
 * @method integer getId()          Returns the current record's "id" value
 * @method text    getRoom()        Returns the current record's "room" value
 * @method text    getMessage()     Returns the current record's "message" value
 * @method integer getSenderId()    Returns the current record's "sender_id" value
 * @method text    getSender()      Returns the current record's "sender" value
 * @method integer getAllianceId()  Returns the current record's "alliance_id" value
 * @method text    getAlliance()    Returns the current record's "alliance" value
 * @method Chat    setId()          Sets the current record's "id" value
 * @method Chat    setRoom()        Sets the current record's "room" value
 * @method Chat    setMessage()     Sets the current record's "message" value
 * @method Chat    setSenderId()    Sets the current record's "sender_id" value
 * @method Chat    setSender()      Sets the current record's "sender" value
 * @method Chat    setAllianceId()  Sets the current record's "alliance_id" value
 * @method Chat    setAlliance()    Sets the current record's "alliance" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chat');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('room', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('message', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('sender_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('sender', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('alliance_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('alliance', 'text', null, array(
             'type' => 'text',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}