<?php

/**
 * BaseChat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $room
 * @property integer $player_id
 * @property text $message
 * @property array $user_card
 * 
 * @method integer getId()        Returns the current record's "id" value
 * @method text    getRoom()      Returns the current record's "room" value
 * @method integer getPlayerId()  Returns the current record's "player_id" value
 * @method text    getMessage()   Returns the current record's "message" value
 * @method array   getUserCard()  Returns the current record's "user_card" value
 * @method Chat    setId()        Sets the current record's "id" value
 * @method Chat    setRoom()      Sets the current record's "room" value
 * @method Chat    setPlayerId()  Sets the current record's "player_id" value
 * @method Chat    setMessage()   Sets the current record's "message" value
 * @method Chat    setUserCard()  Sets the current record's "user_card" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseChat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('chat');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('room', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('player_id', 'integer', null, array(
             'type' => 'integer',
             ));
        $this->hasColumn('message', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('user_card', 'array', null, array(
             'type' => 'array',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $timestampable0 = new Doctrine_Template_Timestampable(array(
             'updated' => 
             array(
              'disabled' => true,
             ),
             ));
        $this->actAs($timestampable0);
    }
}