<?php

/**
 * BaseGarrisonBoost
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $type
 * @property float $value
 * 
 * @method integer       getId()    Returns the current record's "id" value
 * @method text          getType()  Returns the current record's "type" value
 * @method float         getValue() Returns the current record's "value" value
 * @method GarrisonBoost setId()    Sets the current record's "id" value
 * @method GarrisonBoost setType()  Sets the current record's "type" value
 * @method GarrisonBoost setValue() Sets the current record's "value" value
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseGarrisonBoost extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('garrison_boosts');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'autoincrement' => true,
             'primary' => true,
             ));
        $this->hasColumn('type', 'text', null, array(
             'type' => 'text',
             ));
        $this->hasColumn('value', 'float', null, array(
             'type' => 'float',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}