<?php

/**
 * BaseEquipment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property text $type
 * @property Doctrine_Collection $levels
 * 
 * @method integer             getId()     Returns the current record's "id" value
 * @method text                getType()   Returns the current record's "type" value
 * @method Doctrine_Collection getLevels() Returns the current record's "levels" collection
 * @method Equipment           setId()     Sets the current record's "id" value
 * @method Equipment           setType()   Sets the current record's "type" value
 * @method Equipment           setLevels() Sets the current record's "levels" collection
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseEquipment extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('equipment');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('type', 'text', null, array(
             'type' => 'text',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('EquipmentLevel as levels', array(
             'local' => 'id',
             'foreign' => 'equipment_id'));
    }
}