<?php

/**
 * AllianceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class AllianceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object AllianceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Alliance');
    }
}