<?php

/**
 * BuildingLevelsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BuildingLevelsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BuildingLevelsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BuildingLevels');
    }
}