<?php

/**
 * BuildingLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class BuildingLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object BuildingLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('BuildingLevel');
    }
}