<?php

/**
 * CampaignStageUnitTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CampaignStageUnitTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CampaignStageUnitTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CampaignStageUnit');
    }
}