<?php

/**
 * ClientHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ClientHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ClientHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ClientHistory');
    }
}