<?php

/**
 * CraftingRecipeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CraftingRecipeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CraftingRecipeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CraftingRecipe');
    }
}