<?php

/**
 * DefenseTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DefenseTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DefenseTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Defense');
    }
}