<?php

/**
 * EquipmentLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EquipmentLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EquipmentLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EquipmentLevel');
    }
}