<?php

/**
 * ForceLeaderboardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ForceLeaderboardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ForceLeaderboardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ForceLeaderboard');
    }
}