<?php

/**
 * GarrisonBoostTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GarrisonBoostTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GarrisonBoostTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GarrisonBoost');
    }
}