<?php

/**
 * GeneralTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneralTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneralTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('General');
    }
}