<?php

/**
 * GeneralLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GeneralLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GeneralLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('GeneralLevel');
    }
}