<?php

/**
 * MapNodeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapNodeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapNodeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MapNode');
    }
}