<?php

/**
 * MapRevardTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MapRevardTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MapRevardTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('MapRevard');
    }
}