<?php

/**
 * MeltdownTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MeltdownTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object MeltdownTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Meltdown');
    }
    
    public static function getCurrent()
    {
    	$result = self::getInstance()
    		->createQuery()
    		->select('value')
    		->orderBy('id DESC')
    		->limit(1)
    		->execute(null, Doctrine::HYDRATE_SINGLE_SCALAR);
    	
    	return $result;
    }
}