<?php

/**
 * MeltdownTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class MeltdownTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object MeltdownTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Meltdown');
    }

    public static function setCurrent($value) {
        $query = MeltdownTable::getInstance()
                ->createQuery()
                ->where('created_at >= ?', date('Y-m-d H:i:s', strtotime('-1 hour')))
                ->andWhere('value = ?', $value);

        if ($query->count() == 0) {
            $record = new Meltdown();
            $record->value = $value;
            $record->save();
            $record->free(true);
            unset($record);
        }
        else {
            $value = self::getCurrent();
        }

        $query->free();
        unset($query);
        return $value;
    }

    public static function getCurrent() {
        $query = self::getInstance()
                ->createQuery()
                ->select('value')
                ->where('created_at >= ?', date('Y-m-d H:i:s', strtotime('-1 hour')))
                ->orderBy('id DESC')
                ->limit(1);

        $result = $query->execute(null, Doctrine::HYDRATE_SINGLE_SCALAR);

        $query->free();
        unset($query);

        return $result;
    }

}
