<?php

/**
 * PlayerHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PlayerHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PlayerHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PlayerHistory');
    }
}