<?php

/**
 * ProxyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ProxyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ProxyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Proxy');
    }
}