<?php

/**
 * Research
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Research extends BaseResearch
{
	public function getTime()
	{
		$result = array();
		foreach($this->levels as $level)
		{
			$result[] = intval($level->time);
		}
		return $result;
	}
	
	public function getResources()
	{
		$result = array();
		foreach($this->levels as $level)
		{
			foreach($level->requirements['resources'] as $resource => $amount)
			{
				if($amount && !in_array($resource, $result))
				{
					$result[] = $resource;
				}
			}
		}
		return $result;
	}
	
	public function getResourceValues($type)
	{
		$result = array();
		foreach($this->levels as $level)
		{
			$result[] = isset($level->requirements['resources'][$type]) ? intval($level->requirements['resources'][$type]) : null; 
		}
		return $result;
	}
	
	public function getBuildings()
	{
		$result = array();
		foreach($this->levels as $level)
		{
			if(isset($level->requirements['buildings']))
			{
				foreach($level->requirements['buildings'] as $building => $building_level)
				{
					if(!in_array($building, $result))
					{
						$result[] = $building;
					}
				}
			}
		}
		return $result;
	}
	
	public function getBuildingValues($type)
	{
		$result = array();
		foreach($this->levels as $level)
		{
			$result[] = (isset($level->requirements['buildings']) && isset($level->requirements['buildings'][$type])) ? intval($level->requirements['buildings'][$type]) : null;
		}
		return $result;
	}
	
	public function getItems()
	{
		$result = array();
		foreach($this->levels as $level)
		{
			if(isset($level->requirements['items']))
			{
				foreach($level->requirements['items'] as $item => $amount)
				{
					if(!in_array($item, $result))
					{
						$result[] = $item;
					}
				}
			}
		}
		return $result;
	}
	
	public function getItemValues($type)
	{
		$result = array();
		foreach($this->levels as $level)
		{
			$result[] = (isset($level->requirements['items']) && isset($level->requirements['items'][$type])) ? $level->requirements['items'][$type] : null;
		}
		return $result;
	}
	
	
}
