<?php

/**
 * ResearchLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResearchLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResearchLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ResearchLevel');
    }
}