<?php

/**
 * ResearchTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ResearchTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ResearchTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Research');
    }
}