<?php

/**
 * SkillLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SkillLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SkillLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('SkillLevel');
    }
}