<?php

/**
 * Skill
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    edgeworld
 * @subpackage model
 * @author     BRIGADA
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Skill extends BaseSkill
{
	public function requirementsSP()
	{
		$result = array();
		foreach($this->levels as $level)
		{
			$result[] = $level->requirements['sp'];
		}
		return $result;
	}
	
	public function stats()
	{
		$result = array();
		foreach ($this->levels as $level)
		{
			foreach($level->stats as $stat => $value)
			{
				if($value && !in_array($stat, $result))
				{
					$result[] = $stat;
				}
			}
		}
		return $result;
	}
	
	public function stat($type)
	{
		$result = array();
		foreach ($this->levels as $level)
		{
			$result [] = $level->stats[$type];
		}
		return $result;
	}
}
