<?php

/**
 * UnitLevelsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitLevelsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitLevelsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnitLevels');
    }
}