<?php

/**
 * UnitLevelTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UnitLevelTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UnitLevelTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UnitLevel');
    }
}