# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: common, action: index }

equipment-info:
  url: /equipment-info/:type
  param: { module: equipment, action: info }

manifest-update:
  url: /manifest/update
  param: { module: manifest, action: update }
  
manifest-equipments:
  url: /manifest/equipments
  param: { module: manifest, action: equipments }

manifest-equipment-update:
  url: /manifest/equipment/update
  param: { module: manifest, action: equipmentUpdate }

manifest-equipment:
  url: /manifest/equipment/:type
  param: { module: manifest, action: equipment }

manifest-buildings:
  url: /manifest/buildings
  param: {module: manifest, action: buildings}

manifest-building:
  url: /manifest/building/:type
  param: {module: manifest, action: building}

manifest-items:
  url: /manifest/items
  param: { module: manifest, action: items }

manifest-item-update:
  url: /manifest/item-update
  param: { module: manifest, action: itemUpdate }

manifest-item:
  url: /manifest/item/:type
  param: { module: manifest, action: item, mode: byType }

manifest-units:
  url: /manifest/units
  param: { module: manifest, action: units }

manifest-units-compare:
  url: /manifest/units/compare
  param: { module: manifest, action unitsCompare }

manifest-unit:
  url: /manifest/unit/:type
  param: { module: manifest, action: unit }

manifest-generals:
  url: /manifest/generals
  param: { module: manifest, action: generals }

manifest-generals-compare:
  url: /manifest/generals/compare
  param: { module: manifest, action: generalsCompare }

manifest-general:
  url: /manifest/general/:type
  param: { module: manifest, action: general }

manifest-skills:
  url: /manifest/skills
  param: { module: manifest, action: skills }

manifest-skill:
  url: /manifest/skill/:type
  param: { module: manifest, action: skill }

manifest-store:
  url: /manifest/store
  param: { module: manifest, action: store }

manifest-researches:
  url: /manifest/researches
  param: { module: manifest, action: researches }
  
manifest-research:
  url: /manifest/research/:type
  param: { module: manifest, action: research }
  
manifest-defenses:
  url: /manifest/defenses
  param: { module: manifest, action: defenses }  
  
manifest-defense:
  url: /manifest/defense/:type
  param: { module: manifest, action: defense }  
  
manifest-campaigns:
  url: /manifest/campaigns
  param: { module: manifest, action: campaigns }

manifest-campaign-update:
  url: /manifest/update/campaign
  param: { module: manifest, action: campaignUpdate }

manifest-campaign:
  url: /manifest/campaign/:id
  param: { module: manifest, action: campaign }

manifest-recipes:
  url: /manifest/recipes
  param: { module: manifest, action: recipes }
  
manifest-recipe:
  url: /manifest/recipe/:name
  param: { module: manifest, action: recipe }
  
manifest-tokens:
  url: /manifest/tokens
  param: { module: manifest, action: tokens }
  
manifest-token:
  url: /manifest/token/:type
  param: { module: manifest, action: token }
  

maps:
  url: /maps
  param: { module: map, action: index }

map-show:
  url: /map/:pos
  param: { module: map, action: show }
  
chat-read:
  url: /chat-read/:room
  param: { module: chat, action: read }

mail:
  url: /mail
  param: { module: mail, action: index }
  
mail-read:
  url: /mail/read
  param: { module: mail, action: read }


# generic rules
# please, remove them by adding more specific rules

default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
