Equipment:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    type:
      type: text
      notnull: true

EquipmentLevel:
  columns:
    equipment_id:
      type: integer
      primary: true
      notnull: true
    level:
      type: integer
      primary: true
      notnull: true
    
    tier: integer
    time: integer
    upgrade_chance: integer
    
    requirements: array
    stats: array
    tags: array

  relations:
    rel_equipment:
      class: Equipment
      local: equipment_id
      foreign: id
      alias: equipment
      foreignAlias: levels
      onDelete: CASCADE
      onUpdate: CASCADE
      
Building:
  tableName: buildings
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    type:
      type: text
      notnull: true
    size_x:
      type: integer
      notnull: true
    size_y:
      type: integer
      notnull: true

BuildingLevels:
  tableName: building_levels
  columns:
    building_id:
      type: integer
      primary: true
      notnull: true
    level:
      type: integer
      primary: true
      notnull: true
    time: integer
    requirements: array
    stats: array
  relations:
    rel_building:
      class: Building
      local: building_id
      foreign: id
      alias: building
      foreignAlias: levels
      onUpdate: CASCADE
      onDelete: CASCADE

General:
  tableName: generals
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    type: text

GeneralLevel:
  tableName: general_levels
  columns:
    general_id:
      type: integer
      primary: true
      notnull: true
    level:
      type: integer
      primary: true
      notnull: true
    requirements: array
    stats: array
    skills: array
    
  relations:
    rel_general:
      class: General
      local: general_id
      foreign: id
      alias: general
      foreignAlias: levels
      onUpdate: CASCADE
      onDelete: CASCADE

MapRevard:
  tableName: map_rewards
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    value: integer
    rewards: array

Unit:
  tableName: units
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    type: text

UnitLevel:
  tableName: unit_levels
  columns:
    unit_id:
      type: integer
      primary: true
      notnull: true
    level:
      type: integer
      primary: true
      notnull: true
    time: integer
    requirements: array
    stats: array
  options:
    order_by: unit_id, level
  relations:
    rel_unit:
      class: Unit
      local: unit_id
      foreign: id
      alias: unit
      foreignAlias: levels
      onUpdate: CASCADE
      onDelete: CASCADE

Skill:
  tableName: skills
  columns:
    id:
      type: integer
      autoincrement: true
      primary: true
    type: text

SkillLevel:
  tableName: skill_levels
  columns:
    skill_id:
      type: integer
      primary: true
      notnull: true
    level:
      type: integer
      primary: true
      notnull: true
    requirements: array
    stats: array
  relations:
    rel_skill:
      class: Skill
      local: skill_id
      foreign: id
      alias: skill
      foreignAlias: levels
      orderBy: level
      onUpdate: CASCADE
      onDelete: CASCADE

Proxy:
  actAs:
    Timestampable:
      updated:
        disabled: true
    
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    type: text
    params: array

Alliance:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    name: text
    description: text
    active: boolean
Player:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    name: text
    
    
PlayerHistory:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    player_id:
      type: integer
      notnull: true
    

Chat:
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      
    room: text
    player_id: integer
    message: text
    user_card: array
    
Map:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    sector: integer
    width: integer
    height: integer
    chunk_size: integer
    outpost_levels: array
    upgrade_costs: object
    max_territory_limit: integer
    type: text
    active: boolean
    maximum_node_level: integer
    
MapNode:
  actAs:
    Timestampable: ~
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    map_id:
      type: integer
      notnull: true
    x:
      type: integer
      notnull: true
    y: 
      type: integer
      notnull: true
    owner:
      type: text
    owner_id:
      type: integer
    collection:
      type: text
      default: null
    collection_id:
      type: integer
      default: null
  relations:
    rel_map:
      class: Map
      local: map_id
      foreign: id
      alias: map
      foreignAlias: nodes
      onDelete: CASCADE
      onUpdate: CASCADE
      
Alliance:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    name:
      type: text
      notnull: true

Player:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    name: text
    level: integer
    mainbase_id: integer
    colonies: array
    alliance_id: integer
    created_at: datetime
    login_at: datetime
    xp: integer
    sp: integer

Home:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    name: text
    damage_protection: datetime
    
ClientHistory:
  actAs:
    Timestampable:
      updated:
        disabled: true
  columns:
    host: text
    meltdown: text
    reactor: text
    user_id: integer
    _session_id: text

Item:
  tableName: items
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    type:
      type: text
      notnull: true      
    permanent:
      type: boolean
      default: false
      notnull: true
    
    boost_amount: integer
    boost_percentage: integer
    boost_type: text
    
    resource_amount: integer
    resource_type: text
    
    contents: array
    tags: array

Campaign:
  tableName: campaigns
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    name: text
    unlock_level: integer
  relations:
    rel_stages:
      class: CampaignStage
      local: id
      foreign: campaign_id
      alias: stages
      type: many
      foreignType: one
      foreignAlias: campaign
      owningSide: false
      onDelete: CASCADE
      onUpdate: CASCADE
      orderBy: id
    
CampaignStage:
  tableName: campaigns_stages
  columns:
    id:
      type: integer
      notnull: true
      primary: true
    campaign_id:
      type: integer
      notnull: true
    name: text
    attacker_level: integer
    attacker_boost: float
    unit_level: integer
    baseline_xp: integer
    player_unlock_level: integer
  relations:
    rel_stage:
      class: CampaignStageUnit
      local: id
      foreign: stage_id
      alias: units
      type: many
      foreignType: one
      foreignAlias: stage
      onDelete: CASCADE
      onUpdate: CASCADE
      owningSide: false
      orderBy: time, id

CampaignStageUnit:
  tableName: campaigns_stages_units
  columns:
    stage_id:
      type: integer
      notnull: true
    type: text
    quantity: integer
    x: integer
    y: integer
    time: integer

Defense:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    type:
      type: text
      notnull: true
  relations:
    rel_levels:
      class: DefenseLevel
      local: id
      foreign: defense_id
      alias: levels
      type: many
      orderBy: level
      owningSide: false

DefenseLevel:
  tableName: defense_levels
  columns:
    defense_id:
      type: integer
      primary: true
      notnull: true
    level:
      type: integer
      primary: true
      notnull: true
    time: integer
    requirements: array
    stats: array
  relations:
    rel_defense:
      class: Defense
      local: defense_id
      foreign: id
      alias: defense
      onDelete: CASCADE
      onUpdate: CASCADE
      owningSide: true

Research:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    type:
      type: text
      notnull: true

ResearchLevel:
  tableName: research_levels
  columns:
    research_id:
      type: integer
      primary: true
      notnull: true
    level:
      type: integer
      primary: true
      notnull: true
    time: integer
    requirements: array
  relations:
    rel_reseach:
      class: Research
      local: research_id
      foreign: id
      type: one
      foreignType: many
      alias: research
      foreignAlias: levels
      onDelete: CASCADE
      onUpdate: CASCADE
        
#Requirement:
#  tableName: requirements
#  columns:
#    id:
#      type: integer
#      primary: true
#      autoincrement: true
#    sp: integer

ForceTournament:
  columns:
    id:
      type: integer
      primary: true
      notnull: true
    dates: text
    sector: integer    
    type: text
    end_at: integer
    daily_prizing: array
    bout_prizing: array
    challenge_prizing: array
    active_calculations: array
    value_adjustments: array

ForceLeaderboard:
  columns:
    tournament_id:
      type: integer
      primary: true
    timestamp:
      type: integer
      primary: true
    rank:
      type: integer
      primary: true
    user_id: integer
    user_name: text
    power: integer
  relations:
    rel_tournament:
      class: ForceTournament
      local: tournament_id
      foreign: id
    